# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S72dD0LRVicFPKcQLIQBXuIQYlbmMg66
"""

import pandas as pd
import difflib

# Load your medicine database
df = pd.read_csv("/content/updated_indian_medicine_data.csv", encoding='ISO-8859-1')
df.fillna('', inplace=True)
df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)
# Check the column names in the dataset
print(df.columns)

# Now run the rest of your code

# Function to find best matches from user text input
def find_best_matches_from_text(user_text, df, top_n=3):
    matches = []
    for _, row in df.iterrows():
        row_text = f"{row['medicine_desc']}"
        score = difflib.SequenceMatcher(None, user_text.lower(), row_text).ratio()
        matches.append((score, row))

    matches.sort(reverse=True, key=lambda x: x[0])
    return [match[1] for match in matches[:top_n]]

# 👉 You can change this text based on what you see on the medicine or what user types
user_input_text = input("Paste the text you see on the medicine (or describe it): ")

# Get top matches
top_matches = find_best_matches_from_text(user_input_text, df)

# Show results
print("\n🔍 Top Matching Medicines:")
for i, match in enumerate(top_matches, 1):
    print(f"\n{i}. Brand: {match['name'].title()}")
    print(f"   Price: {match['price']}")
    print(f"   Side effect: {match['side_effects']}")